---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-example-dev
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
